services:
  activity-service:
    build: ./services/activity-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - fittrack-network

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - fittrack-network

networks:
  fittrack-network:
    driver: bridge