version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - fittrack-network
    depends_on:
      - activity-service
      - user-service

  activity-service:
    build: ./services/activity-service
    networks:
      - fittrack-network

  user-service:
    build: ./services/user-service
    networks:
      - fittrack-network

networks:
  fittrack-network:
    driver: bridge